"""
Build DevOps_Laboratory_Manual.pdf from DevOps_Laboratory_Manual.md
using python-markdown + WeasyPrint.
"""

import re
from pathlib import Path

import markdown
from pygments.formatters import HtmlFormatter
from weasyprint import HTML

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO = Path(__file__).parent
MD_SRC = REPO / "DevOps_Laboratory_Manual.md"
PDF_OUT = REPO / "DevOps_Laboratory_Manual.pdf"

# ---------------------------------------------------------------------------
# Read source
# ---------------------------------------------------------------------------
md_text = MD_SRC.read_text(encoding="utf-8")

# ---------------------------------------------------------------------------
# python-markdown conversion
# ---------------------------------------------------------------------------
extensions = [
    "markdown.extensions.tables",
    "markdown.extensions.fenced_code",
    "markdown.extensions.toc",
    "markdown.extensions.attr_list",
    "markdown.extensions.sane_lists",
    "markdown.extensions.codehilite",
]

ext_configs = {
    "markdown.extensions.toc": {
        "toc_depth": "2-2",   # Only H2 in TOC (experiments + preface)
        "permalink": False,
        "anchorlink": False,
    },
    "markdown.extensions.codehilite": {
        "linenums": False,
        "use_pygments": True,
        "pygments_style": "monokai",
        "noclasses": False,
        "guess_lang": False,
    },
}

md_proc = markdown.Markdown(extensions=extensions, extension_configs=ext_configs)
body_html = md_proc.convert(md_text)
toc_html = md_proc.toc   # Generated TOC as HTML string

# Official experiment questions used verbatim in the TOC.
# Keys are the anchor IDs generated by python-markdown from the H2 headings.
# The heading text inside the manual body is NOT changed — only the TOC label.
_TOC_LABELS: dict[str, str] = {
    "#experiment-01-event-registration-web-application":
        "Write code for a simple user registration form for an event.",
    "#experiment-02-explore-git-and-github-commands":
        "Explore Git and GitHub commands.",
    "#experiment-03-practice-source-code-management-on-github":
        "Practice Source code management on GitHub. "
        "Experiment with the source code in exercise 1.",
    "#experiment-04-jenkins-installation-and-setup":
        "Jenkins installation and setup, explore the environment.",
    "#experiment-05-demonstrate-cicd-using-jenkins":
        "Demonstrate continuous integration and development using Jenkins.",
    "#experiment-06-explore-docker-commands-for-content-management":
        "Explore Docker commands for content management.",
    "#experiment-07-build-and-run-an-application-using-a-dockerfile-then-create-a-new-image-version-after-modifying-the-application":
        "Develop a simple containerized application using Docker.",
    "#experiment-08-deploy-the-dockerized-application-to-kubernetes":
        "Integrate Kubernetes and Docker.",
    "#experiment-09-automate-the-process-of-running-the-containerized-application-using-kubernetes":
        "Automate the process of running containerized application "
        "for exercise 7 using Kubernetes.",
    "#experiment-10-selenium-automated-testing":
        "Install and Explore Selenium for automated testing.",
    "#experiment-11-javascript-calculator-selenium-automated-testing":
        "Write a simple JavaScript program and perform testing using Selenium.",
    "#experiment-12-develop-test-cases-for-the-containerized-application-using-selenium":
        "Develop test cases for the above containerized application using selenium.",
}

# Build a 3-column TOC table: Exp. | Name of the Question | Page.
# Experiment entries use the official question text; other entries (Preface) keep
# the heading text derived from the markdown.
def _build_toc_table(raw_toc: str) -> str:
    rows = []
    for m in re.finditer(r'<a href="(#[^"]+)">([^<]+)</a>', raw_toc):
        href = m.group(1)
        title = m.group(2).strip()
        exp_m = re.search(r'experiment-(\d+)-', href)
        if exp_m:
            exp_cell = exp_m.group(1).zfill(2)
            label = _TOC_LABELS.get(href, title)
            name_cls = "toc-td-name"
        else:
            exp_cell = "&#8212;"  # em dash for non-experiment entries
            label = title
            name_cls = "toc-td-name toc-preface"
        rows.append(
            f'<tr>'
            f'<td class="toc-td-exp">{exp_cell}</td>'
            f'<td class="{name_cls}"><a href="{href}" class="toc-name-link">{label}</a></td>'
            f'<td class="toc-td-page"><a href="{href}" class="toc-pglink"></a></td>'
            f'</tr>'
        )
    return (
        '<table class="toc-table">\n'
        '<thead><tr>'
        '<th class="toc-th-exp">Exp.</th>'
        '<th class="toc-th-name">Name of the Question</th>'
        '<th class="toc-th-page">Page</th>'
        '</tr></thead>\n'
        f'<tbody>\n{"".join(rows)}\n</tbody>\n'
        '</table>'
    )

toc_html = _build_toc_table(toc_html)

# ---------------------------------------------------------------------------
# Pygments CSS (monokai style)
# ---------------------------------------------------------------------------
pygments_css = HtmlFormatter(style="monokai").get_style_defs(".codehilite")

# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------
MAIN_CSS = f"""
/* ============================================================
   FONTS
   ============================================================ */
@font-face {{
    font-family: 'body-font';
    src: local('DejaVu Serif');
    font-weight: normal;
}}
@font-face {{
    font-family: 'body-font';
    src: local('DejaVu Serif');
    font-weight: bold;
}}

/* ============================================================
   PAGE LAYOUT
   ============================================================ */
@page {{
    size: A4;
    margin: 26mm 20mm 22mm 20mm;

    @top-left {{
        content: "DevOps Laboratory Manual";
        font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
        font-size: 8pt;
        font-weight: bold;
        color: #1e3a5f;
        vertical-align: bottom;
        padding-bottom: 5pt;
        border-bottom: 1.5pt solid #1e3a5f;
        width: 55%;
    }}

    @top-right {{
        content: string(chapter-title);
        font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
        font-size: 7pt;
        color: #4a6580;
        vertical-align: bottom;
        padding-bottom: 5pt;
        border-bottom: 1.5pt solid #1e3a5f;
        text-align: right;
        width: 45%;
    }}

    @bottom-center {{
        content: counter(page);
        font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
        font-size: 9pt;
        color: #1e3a5f;
        font-weight: bold;
        vertical-align: top;
        padding-top: 5pt;
        border-top: 1pt solid #1e3a5f;
        width: 100%;
        text-align: center;
    }}
}}

/* TOC pages — fixed "Table of Contents" in the right header slot */
@page toc-page {{
    size: A4;
    margin: 26mm 20mm 22mm 20mm;

    @top-left {{
        content: "DevOps Laboratory Manual";
        font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
        font-size: 8pt;
        font-weight: bold;
        color: #1e3a5f;
        vertical-align: bottom;
        padding-bottom: 5pt;
        border-bottom: 1.5pt solid #1e3a5f;
        width: 55%;
    }}

    @top-right {{
        content: "Table of Contents";
        font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
        font-size: 7.5pt;
        color: #4a6580;
        vertical-align: bottom;
        padding-bottom: 5pt;
        border-bottom: 1.5pt solid #1e3a5f;
        text-align: right;
        width: 45%;
    }}

    @bottom-center {{
        content: counter(page);
        font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
        font-size: 9pt;
        color: #1e3a5f;
        font-weight: bold;
        vertical-align: top;
        padding-top: 5pt;
        border-top: 1pt solid #1e3a5f;
        width: 100%;
        text-align: center;
    }}
}}

/* ============================================================
   BASE TYPOGRAPHY
   ============================================================ */
* {{
    box-sizing: border-box;
}}

body {{
    font-family: 'DejaVu Serif', Georgia, serif;
    font-size: 10.5pt;
    line-height: 1.55;
    color: #1a1a1a;
    margin: 0;
    padding: 0;
    hyphens: none;
}}

/* ============================================================
   HORIZONTAL RULES — hidden: headings and page breaks
   provide all visual separation; HR elements from Markdown
   "---" separators only create orphaned lines at page bottoms
   ============================================================ */
hr {{
    display: none;
}}

/* ============================================================
   TITLE (H1 — appears once, at top of TOC page)
   ============================================================ */
h1 {{
    font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
    font-size: 26pt;
    font-weight: bold;
    color: #1e3a5f;
    text-align: center;
    margin: 0 0 6pt 0;
    padding: 20pt 0 14pt 0;
    letter-spacing: 0.5pt;
    border-bottom: 3pt solid #1e3a5f;
    page-break-after: avoid;
}}

/* Subtitle line under H1 */
h1 + p {{
    text-align: center;
    color: #4a6580;
    font-style: italic;
    font-size: 10pt;
    margin-top: 4pt;
    margin-bottom: 0;
}}

/* ============================================================
   EXPERIMENT HEADINGS (H2)
   ============================================================ */
h2 {{
    font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
    font-size: 15pt;
    font-weight: bold;
    color: #ffffff;
    background-color: #1e3a5f;
    margin: 0 0 10pt 0;
    padding: 10pt 14pt;
    page-break-before: always;
    page-break-after: avoid;
    border-radius: 3pt;
    string-set: chapter-title content();
    letter-spacing: 0.3pt;
}}

/* The Preface H2 is the first element in .content — the toc-wrapper's
   page-break-after already creates the break, so suppress the duplicate
   page-break-before to avoid a blank page between TOC and Preface. */
.content > h2:first-child {{
    page-break-before: auto;
}}

/* TOC H2 ("Table of Contents") — different styling, no background */
.toc-wrapper h2 {{
    page-break-before: avoid;
    background: none;
    color: #1e3a5f;
    border-bottom: 2pt solid #1e3a5f;
    border-radius: 0;
    padding: 0 0 6pt 0;
    margin-bottom: 12pt;
    font-size: 18pt;
    string-set: none;
}}

/* ============================================================
   SECTION HEADINGS (H3)
   ============================================================ */
h3 {{
    font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
    font-size: 12pt;
    font-weight: bold;
    color: #1e3a5f;
    margin: 12pt 0 5pt 0;
    padding: 5pt 0 5pt 10pt;
    border-left: 4pt solid #2d6da3;
    page-break-after: avoid;
    background: #f7f9fc;
}}

/* ============================================================
   SUB-SECTION HEADINGS (H4)
   ============================================================ */
h4 {{
    font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
    font-size: 10.5pt;
    font-weight: bold;
    color: #1e3a5f;
    margin: 9pt 0 4pt 0;
    padding: 3pt 0 3pt 8pt;
    border-left: 2.5pt solid #6b9dc4;
    page-break-after: avoid;
}}

h5, h6 {{
    font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
    font-size: 10pt;
    font-weight: bold;
    color: #2d4a6b;
    margin: 8pt 0 4pt 0;
    page-break-after: avoid;
}}

/* ============================================================
   PARAGRAPHS
   ============================================================ */
p {{
    margin: 0 0 7pt 0;
    orphans: 2;
    widows: 2;
    text-align: left;
}}

/* ============================================================
   LISTS
   ============================================================ */
ul, ol {{
    margin: 4pt 0 8pt 0;
    padding-left: 22pt;
}}

li {{
    margin-bottom: 3pt;
    line-height: 1.55;
}}

li > ul, li > ol {{
    margin-top: 2pt;
    margin-bottom: 2pt;
}}

/* ============================================================
   CODE — INLINE
   ============================================================ */
code {{
    font-family: 'Ubuntu Mono', 'DejaVu Sans Mono', monospace;
    font-size: 9pt;
    background-color: #f0f4f8;
    color: #1e3a5f;
    padding: 1pt 3pt;
    border-radius: 2pt;
    border: 0.5pt solid #d0dde8;
    word-break: break-word;
}}

/* ============================================================
   CODE BLOCKS (fenced / codehilite)
   Long code blocks (index.html, Jenkinsfile, test scripts) can
   exceed a full page, so page-break-inside is NOT avoided —
   WeasyPrint continues the dark background across the page break,
   making it visually clear the code continues.
   ============================================================ */
.codehilite {{
    background: #272822;
    border-radius: 4pt;
    border: 1pt solid #444;
    padding: 0;
    margin: 8pt 0 10pt 0;
}}

.codehilite pre {{
    font-family: 'Ubuntu Mono', 'DejaVu Sans Mono', monospace;
    font-size: 8.2pt;
    line-height: 1.45;
    color: #f8f8f2;
    margin: 0;
    padding: 10pt 12pt;
    white-space: pre-wrap;
    word-break: break-word;
    overflow-wrap: anywhere;
    background: transparent;
}}

.codehilite code {{
    font-family: 'Ubuntu Mono', 'DejaVu Sans Mono', monospace;
    font-size: 8.2pt;
    background: transparent;
    border: none;
    padding: 0;
    color: #f8f8f2;
    word-break: break-word;
}}

/* Plain pre/code (not via codehilite) */
pre {{
    font-family: 'Ubuntu Mono', 'DejaVu Sans Mono', monospace;
    font-size: 8.2pt;
    background: #272822;
    color: #f8f8f2;
    border-radius: 4pt;
    border: 1pt solid #444;
    padding: 10pt 12pt;
    margin: 8pt 0 10pt 0;
    white-space: pre-wrap;
    word-break: break-word;
    overflow-wrap: anywhere;
    line-height: 1.45;
}}

pre code {{
    font-family: 'Ubuntu Mono', 'DejaVu Sans Mono', monospace;
    background: transparent;
    border: none;
    padding: 0;
    color: #f8f8f2;
    font-size: inherit;
    word-break: break-word;
}}

/* ============================================================
   TABLES
   page-break-inside: avoid keeps short reference/verification
   tables on one page; WeasyPrint overrides for tables taller
   than a full page (best-effort constraint).
   thead repeats automatically when a table breaks.
   ============================================================ */
table {{
    width: 100%;
    border-collapse: collapse;
    margin: 10pt 0 12pt 0;
    font-size: 9.5pt;
    page-break-inside: avoid;
    break-inside: avoid;
}}

thead {{
    display: table-header-group;
}}

thead tr {{
    background-color: #1e3a5f;
    color: #ffffff;
}}

thead th {{
    padding: 6pt 8pt;
    text-align: left;
    font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
    font-size: 9pt;
    font-weight: bold;
    border: 0.5pt solid #14284a;
    letter-spacing: 0.2pt;
    word-break: break-word;
}}

tbody tr:nth-child(odd) {{
    background-color: #f7f9fc;
}}

tbody tr:nth-child(even) {{
    background-color: #eef2f7;
}}

tbody td {{
    padding: 5pt 8pt;
    border: 0.5pt solid #c8d8e8;
    vertical-align: top;
    line-height: 1.4;
    word-break: break-word;
    overflow-wrap: anywhere;
}}

/* Give the 4th column (Retry / Next) a minimum width so auto table layout
   cannot collapse it below the width of a short filename or command.
   This applies only when a 4th column exists (Common Mistakes tables). */
.content table th:nth-child(4),
.content table td:nth-child(4) {{
    min-width: 110pt;
}}

/* A table that immediately follows an H3 heading must NOT be pushed to the
   next page — that would strand the heading alone. Also allow such tables to
   break across pages so they are never evicted from the current page when they
   are taller than the remaining space. The global page-break-inside: avoid is
   overridden here because it is what causes the eviction. */
h3 + table {{
    page-break-before: avoid;
    break-before: avoid;
    page-break-inside: auto;
    break-inside: auto;
}}

/* ============================================================
   BLOCKQUOTES / CALLOUTS
   ============================================================ */
blockquote {{
    border-left: 4pt solid #2d6da3;
    margin: 8pt 0 8pt 0;
    padding: 6pt 12pt;
    background: #f0f5fa;
    color: #2d3a4a;
    font-style: italic;
    border-radius: 0 3pt 3pt 0;
    page-break-inside: avoid;
    break-inside: avoid;
}}

blockquote p {{
    margin: 0;
    hyphens: auto;
}}

/* ============================================================
   LINKS
   ============================================================ */
a {{
    color: #1a5fa8;
    text-decoration: underline;
}}

a:visited {{
    color: #5c3a8a;
}}

/* ============================================================
   STRONG / EM
   ============================================================ */
strong {{
    color: #0f2a44;
}}

em {{
    color: #2d3a4a;
}}

/* ============================================================
   PYGMENTS CSS (injected)
   ============================================================ */
{pygments_css}

/* ============================================================
   TABLE OF CONTENTS — 3-column table layout
   Col 1: Exp. number  (fixed 40pt, centered)
   Col 2: Name of the Question  (flexible, wraps naturally within this column)
   Col 3: Page  (fixed 32pt, right-aligned)
   Page numbers are resolved at render time via target-counter.
   ============================================================ */
.toc-wrapper {{
    page: toc-page;
    page-break-after: always;
    padding: 0;
}}

/* Override global table defaults so the TOC table is not constrained by
   the body table font-size (9.5pt) or page-break-inside: avoid. */
.toc-table {{
    width: 100%;
    border-collapse: collapse;
    margin: 0;
    font-size: 10.5pt;
    table-layout: fixed;
    page-break-inside: auto;
    break-inside: auto;
}}

.toc-table thead tr {{
    background-color: #1e3a5f;
    color: #ffffff;
}}

.toc-table thead th {{
    font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
    font-size: 9.5pt;
    font-weight: bold;
    color: #ffffff;
    padding: 7pt 8pt;
    border: 0.5pt solid #14284a;
    letter-spacing: 0.2pt;
}}

.toc-th-exp {{
    width: 40pt;
    text-align: center;
    white-space: nowrap;
}}

.toc-th-name {{
    text-align: left;
}}

.toc-th-page {{
    width: 32pt;
    text-align: right;
    white-space: nowrap;
}}

.toc-table tbody tr:nth-child(odd) {{
    background-color: #f7f9fc;
}}

.toc-table tbody tr:nth-child(even) {{
    background-color: #eef2f7;
}}

.toc-table tbody td {{
    padding: 7pt 8pt;
    border: 0.5pt solid #c8d8e8;
    vertical-align: middle;
    line-height: 1.45;
    font-size: 10.5pt;
}}

/* Experiment number cell — never wraps */
.toc-td-exp {{
    width: 40pt;
    text-align: center;
    font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
    font-weight: bold;
    color: #1e3a5f;
    white-space: nowrap;
    font-size: 10.5pt;
}}

/* Question name cell — wraps within this column only */
.toc-td-name {{
    text-align: left;
    word-break: break-word;
    overflow-wrap: break-word;
}}

/* Link text in name cell — no underline, styled like a heading */
.toc-name-link {{
    font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
    font-size: 10.5pt;
    font-weight: bold;
    color: #1e3a5f;
    text-decoration: none;
}}

/* Preface row — italic, muted to distinguish from numbered experiments */
.toc-preface .toc-name-link {{
    font-style: italic;
    font-weight: normal;
    color: #4a6580;
}}

/* Page number cell — never wraps */
.toc-td-page {{
    width: 32pt;
    text-align: right;
    white-space: nowrap;
    font-family: 'Ubuntu', 'DejaVu Sans', sans-serif;
    color: #4a6580;
    font-size: 10.5pt;
}}

/* Anchor that carries the dynamic page counter — no visible underline */
.toc-pglink {{
    text-decoration: none;
    color: #4a6580;
}}

/* Page number resolved at render time from the target element's page counter */
.toc-pglink::after {{
    content: target-counter(attr(href url), page);
}}

/* ============================================================
   COVER PAGE (page 1 — title only, no header/footer, full-area border)
   ============================================================ */
@page cover-page {{
    size: A4;
    margin: 15mm 15mm 15mm 15mm;

    @top-left {{
        content: none;
        border: none;
    }}

    @top-right {{
        content: none;
        border: none;
    }}

    @bottom-center {{
        content: none;
        border: none;
    }}
}}

/* The border fills the full content area (A4 297mm − 15mm top − 15mm bottom = 267mm). */
.cover-page {{
    page: cover-page;
    page-break-after: always;
    border: 2.5pt solid #1e3a5f;
    height: 267mm;
    width: 100%;
    box-sizing: border-box;
}}

/* Title is visually centred inside the bordered box via top padding.
   border-bottom is removed here — on the cover the outer border is the frame. */
.cover-page h1 {{
    margin: 0;
    padding-top: 105mm;
    border-bottom: none;
    page-break-after: avoid;
}}

/* ============================================================
   AVOID ORPHANED HEADINGS
   ============================================================ */
h2, h3, h4 {{
    page-break-after: avoid;
}}

figure {{
    page-break-inside: avoid;
    break-inside: avoid;
}}
"""

# ---------------------------------------------------------------------------
# Build HTML document
# ---------------------------------------------------------------------------
# Extract H1 text
h1_match = re.match(r"^<h1[^>]*>(.*?)</h1>", body_html, re.DOTALL)
h1_text = h1_match.group(1) if h1_match else "DevOps Laboratory Manual"

# Strip H1 from body
body_without_h1 = re.sub(r"^<h1[^>]*>.*?</h1>", "", body_html, count=1, flags=re.DOTALL)

# Strip any leading <hr> elements that directly follow the H1 (from "---" in Markdown).
# The first H2 (Preface) already starts on a new page via TOC page-break-after;
# the <hr> would otherwise create a stray line at the top of the first content page.
body_without_h1 = re.sub(r"^\s*<hr\s*/?>\s*", "", body_without_h1)

HTML_TEMPLATE = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>DevOps Laboratory Manual</title>
<style>
{MAIN_CSS}
</style>
</head>
<body>

<!-- COVER PAGE (page 1 — title only) -->
<div class="cover-page">
  <h1>{h1_text}</h1>
</div>

<!-- TABLE OF CONTENTS PAGE (page 2) -->
<div class="toc-wrapper">
  <h2 style="page-break-before: avoid; background: none; color: #1e3a5f;
             border-bottom: 2pt solid #1e3a5f; border-radius: 0;
             padding: 0 0 6pt 0; margin-top: 0; margin-bottom: 12pt;
             font-size: 16pt; string-set: none;">
    Table of Contents
  </h2>
  <nav class="toc" aria-label="Table of Contents">
    {toc_html}
  </nav>
</div>

<!-- DOCUMENT BODY (Preface + Experiments 01–12) -->
<main class="content">
{body_without_h1}
</main>

</body>
</html>"""

# ---------------------------------------------------------------------------
# Write intermediate HTML for debugging
# ---------------------------------------------------------------------------
html_debug = REPO / "DevOps_Laboratory_Manual_debug.html"
html_debug.write_text(HTML_TEMPLATE, encoding="utf-8")
print(f"[INFO] Intermediate HTML written to {html_debug}")

# ---------------------------------------------------------------------------
# Generate PDF
# ---------------------------------------------------------------------------
print(f"[INFO] Converting to PDF: {PDF_OUT}")
print("[INFO] This may take 30–90 seconds …")

doc = HTML(string=HTML_TEMPLATE, base_url=str(REPO))
doc.write_pdf(
    PDF_OUT,
    presentational_hints=True,
    optimize_images=True,
)

print(f"[SUCCESS] PDF written to {PDF_OUT}")
print(f"[INFO]    Size: {PDF_OUT.stat().st_size / 1024 / 1024:.1f} MB")
